export const CHART_HEIGHT_STR = "600px";
export const CHART_HEIGHT_NUM= 600;
export const TIDE_CHART_DAYS = 2;
export const STARTING_TIDE_DAYS = 1;
export const CONTENT_DATA = [
  {
    name: "North West",
    station: "51101",
    id: 0,
    tag: "buoy",
    header: "Buoy Station 51101",
    meta: "186 NM NW of Kauai Is",
  },
  {
    name: "Hanalei",
    station: "51208",
    id: 1,
    tag: "buoy",
    header: "Buoy Station 51208",
    meta: "Hanalei, Kauai, HI",
  },
  {
    name: "Hanalei",
    station: "1611683",
    id: 2,
    tag: "tide",
    header: "Tide Predictions at 1611683",
    meta: "Hanalei Bay, HI",
  },
  {
    name: "North West",
    station: "51101",
    id: 3,
    tag: "power",
    header: "Wave Energy for Station 51101",
    meta: "186 NM NW of Kauai Is",
  },
  {
    name: "Hanalei",
    station: "51208",
    id: 4,
    tag: "power",
    header: "Wave Energy for Station 51208",
    meta: "Hanalei, Kauai, HI",
  },
  {
    name: "Southwest Hawaii",
    station: "51002",
    id: 5,
    tag: "buoy",
    header: "Buoy Station 51002",
    meta: "SOUTHWEST HAWAII - 215NM SSW of Hilo, HI",
  },
  {
    name: "Southwest Hawaii",
    station: "51002",
    id: 6,
    tag: "power",
    header: "Wave Energy for Station 51002",
    meta: "SOUTHWEST HAWAII - 215NM SSW of Hilo, HI",
  },
  {
    name: "Western Hawaii",
    station: "51003",
    id: 7,
    tag: "buoy",
    header: "Buoy Station 51003",
    meta: "WESTERN HAWAII - 205 NM SW of Honolulu, HI",
  },
  {
    name: "Western Hawaii",
    station: "51003",
    id: 8,
    tag: "power",
    header: "Wave Energy for Station 51003",
    meta: "WESTERN HAWAII - 205 NM SW of Honolulu, HI",
  },
  {
    name: "Waimea Bay",
    station: "51201",
    id: 9,
    tag: "buoy",
    header: "Buoy Station 51201",
    meta: "WESTERN HAWAII - 205 NM SW of Honolulu, HI",
  },
  {
    name: "Waimea Bay",
    station: "51201",
    id: 10,
    tag: "power",
    header: "Wave Energy for Station 51201",
    meta: "Waimea Bay, HI",
  },
  {
    name: "Honolulu",
    station: "1612340",
    id: 11,
    tag: "tide",
    header: "Tide Predictions at 1612340",
    meta: "Honolulu, HI",
  },
  {
    name: "Haleiwa",
    station: "1612668",
    id: 12,
    tag: "tide",
    header: "Tide Predictions at 1612668",
    meta: "Haleiwa, Waialua Bay, HI",
  },
  {
    name: "Overview",
    station: "0",
    id: 13,
    tag: "forecast",
    header: "All Islands OverviewForecast",
    meta: "Kauai, HI",
  },
  {
    name: "Kauai",
    station: "1",
    id: 14,
    tag: "forecast",
    header: "Kauai Forecast",
    meta: "Kauai, HI",
  },
  {
    name: "O'ahu",
    station: "2",
    id: 15,
    tag: "forecast",
    header: "Oahu Forecast",
    meta: "O'ahu, HI",
  },
  {
    name: "Maui",
    station: "3",
    id: 16,
    tag: "forecast",
    header: "Maui Forecast",
    meta: "Maui, HI",
  },
  {
    name: "Big Island Windward and Southeast",
    station: "4",
    id: 17,
    tag: "forecast",
    header: "Big Island Windward and Southeast",
    meta: "Hawaii, HI",
  },
  {
    name: "Big Island Leeward",
    station: "5",
    id: 18,
    tag: "forecast",
    header: "Big Island Leeward",
    meta: "Hawaii, HI",
  },
  {
    name: "Overview",
    station: "1",
    id: 19,
    tag: "marine-forecast",
    header: "Marine Forecast",
    meta: "Hawaiian Coastal Waters",
  },
  {
    name: "Kauai NorthWest Waters",
    station: "2",
    id: 20,
    tag: "marine-forecast",
    header: "",
    meta: "",
  },
  {
    name: "Kauai Windward Waters",
    station: "3",
    id: 21,
    tag: "marine-forecast",
    header: "",
    meta: "",
  },
  {
    name: "Kauai Leeward Waters",
    station: "4",
    id: 22,
    tag: "marine-forecast",
    header: "",
    meta: "",
  },
  {
    name: "Kauai Channel",
    station: "5",
    id: 23,
    tag: "marine-forecast",
    header: "",
    meta: "",
  },
  {
    name: "Oahu Windward Waters",
    station: "6",
    id: 24,
    tag: "marine-forecast",
    header: "",
    meta: "",
  },
  {
    name: "Oahu Leeward Waters",
    station: "7",
    id: 25,
    tag: "marine-forecast",
    header: "",
    meta: "",
  },
  {
    name: "Ka'iwi Channel",
    station: "8",
    id: 26,
    tag: "marine-forecast",
    header: "",
    meta: "",
  },
  {
    name: "Maui County Windward Waters",
    station: "9",
    id: 27,
    tag: "marine-forecast",
    header: "",
    meta: "",
  },
  {
    name: "Maui County Leeward Waters",
    station: "10",
    id: 28,
    tag: "marine-forecast",
    header: "",
    meta: "",
  },
  {
    name: "Ma'alaea Bay",
    station: "11",
    id: 29,
    tag: "marine-forecast",
    header: "",
    meta: "",
  },
  {
    name: "Pailolo Channel",
    station: "12",
    id: 30,
    tag: "marine-forecast",
    header: "",
    meta: "",
  },
  {
    name: "Alenuihaha Channel",
    station: "13",
    id: 31,
    tag: "marine-forecast",
    header: "",
    meta: "",
  },
  {
    name: "Big Island Windward Waters",
    station: "14",
    id: 32,
    tag: "marine-forecast",
    header: "",
    meta: "",
  },
  {
    name: "Big Island Leeward Waters",
    station: "15",
    id: 33,
    tag: "marine-forecast",
    header: "",
    meta: "",
  },
  {
    name: "Big Island Southeast Waters",
    station: "16",
    id: 34,
    tag: "marine-forecast",
    header: "",
    meta: "",
  },
  {
    name: "Pacific Ocean",
    station: "pac",
    id: 35,
    tag: "wave-model",
    header: "",
    meta: "",
  },
  {
    name: "North Pacific",
    station: "npac",
    id: 36,
    tag: "wave-model",
    header: "",
    meta: "",
  },
  {
    name: "South Pacific",
    station: "spac",
    id: 37,
    tag: "wave-model",
    header: "",
    meta: "",
  },
  {
    name: "Indian Ocean",
    station: "indi",
    id: 38,
    tag: "wave-model",
    header: "",
    meta: "",
  },
  {
    name: "North Atlantic",
    station: "natla",
    id: 39,
    tag: "wave-model",
    header: "",
    meta: "",
  },
  {
    name: "South Atlantic",
    station: "satla",
    id: 40,
    tag: "wave-model",
    header: "",
    meta: "",
  },
  {
    name: "Barber's Point",
    station: "51212",
    id: 41,
    tag: "buoy",
    header: "Buoy Station 51212",
    meta: "Barbers Point, Kalaeloa, HI",
  },
  {
    name: "Barber's Point",
    station: "51212",
    id: 42,
    tag: "power",
    header: "Wave Energy for Station 51212",
    meta: "Barbers Point, Kalaeloa, HI",
  }




];
