export const CHART_HEIGHT = 400;
export const TIDE_CHART_DAYS = 2;
export const CONTENT_DATA = [
  {
    name: "North West",
    station: "51101",
    id: 0,
    tag: "buoy",
    header: "Buoy Station 51101",
    meta: "186 NM NW of Kauai Is",
  },
  {
    name: "Hanalei",
    station: "51208",
    id: 1,
    tag: "buoy",
    header: "Buoy Station 51208",
    meta: "Hanalei, Kauai, HI",
  },
  {
    name: "Hanalei",
    station: "1611683",
    id: 2,
    tag: "tide",
    header: "Tide Predictions at 1611683",
    meta: "Hanalei Bay, HI",
  },
  {
    name: "North West",
    station: "51101",
    id: 3,
    tag: "power",
    header: "Wave Energy for Station 51101",
    meta: "186 NM NW of Kauai Is",
  },
  {
    name: "Hanalei",
    station: "51208",
    id: 4,
    tag: "power",
    header: "Wave Energy for Station 51208",
    meta: "Hanalei, Kauai, HI",
  },
  {
    name: "Southwest Hawaii",
    station: "51002",
    id: 5,
    tag: "buoy",
    header: "Buoy Station 51002",
    meta: "SOUTHWEST HAWAII - 215NM SSW of Hilo, HI",
  },
  {
    name: "Southwest Hawaii",
    station: "51002",
    id: 6,
    tag: "power",
    header: "Wave Energy for Station 51002",
    meta: "SOUTHWEST HAWAII - 215NM SSW of Hilo, HI",
  },
  {
    name: "Western Hawaii",
    station: "51003",
    id: 7,
    tag: "buoy",
    header: "Buoy Station 51003",
    meta: "WESTERN HAWAII - 205 NM SW of Honolulu, HI",
  },
  {
    name: "Western Hawaii",
    station: "51003",
    id: 8,
    tag: "power",
    header: "Wave Energy for Station 51003",
    meta: "WESTERN HAWAII - 205 NM SW of Honolulu, HI",
  },
  {
    name: "Waimea Bay",
    station: "51201",
    id: 9,
    tag: "buoy",
    header: "Buoy Station 51201",
    meta: "WESTERN HAWAII - 205 NM SW of Honolulu, HI",
  },
  {
    name: "Waimea Bay",
    station: "51201",
    id: 10,
    tag: "power",
    header: "Wave Energy for Station 51201",
    meta: "Waimea Bay, HI",
  },
  {
    name: "Honolulu",
    station: "1612340",
    id: 11,
    tag: "tide",
    header: "Tide Predictions at 1612340",
    meta: "Honolulu, HI",
  },
  {
    name: "Haleiwa",
    station: "1612668",
    id: 12,
    tag: "tide",
    header: "Tide Predictions at 1612668",
    meta: "Haleiwa, Waialua Bay, HI",
  },
  {
    name: "Overview",
    station: "0",
    id: 13,
    tag: "forecast",
    header: "Forecast",
    meta: "Kauai, HI",
  },
  {
    name: "Kauai",
    station: "1",
    id: 14,
    tag: "forecast",
    header: "Forecast",
    meta: "Kauai, HI",
  },
  {
    name: "O'ahu",
    station: "2",
    id: 15,
    tag: "forecast",
    header: "Forecast",
    meta: "O'ahu, HI",
  },
  {
    name: "Maui",
    station: "3",
    id: 16,
    tag: "forecast",
    header: "Forecast",
    meta: "Maui, HI",
  },
  {
    name: "Big Island Windward and Southeast",
    station: "4",
    id: 17,
    tag: "forecast",
    header: "Forecast",
    meta: "Hawaii, HI",
  },
  {
    name: "Big Island Leeward",
    station: "5",
    id: 18,
    tag: "forecast",
    header: "Forecast",
    meta: "Hawaii, HI",
  }



];
