export const CONTENT_DATA = [
  {
    name: "North West",
    station: "51001",
    id: 0,
    tag: "buoy",
    header: "Buoy Station 51001",
    meta: "188 NM NW of Kauai Is",
  },
  {
    name: "Hanalei",
    station: "51208",
    id: 1,
    tag: "buoy",
    header: "Buoy Station 51208",
    meta: "Hanalei, Kauai, HI",
  },
  {
    name: "Hanalei",
    station: "1611683",
    id: 2,
    tag: "tide",
    header: "Tide Predictions at 1611683",
    meta: "Hanalei Bay, HI",
  },
  {
    name: "North West",
    station: "51001",
    id: 3,
    tag: "power",
    header: "Wave Energy for Station 51001",
    meta: "186 NM NW of Kauai Is",
  },
  {
    name: "Hanalei",
    station: "51208",
    id: 4,
    tag: "power",
    header: "Wave Energy for Station 51208",
    meta: "Hanalei, Kauai, HI",
  },
  {
    name: "Southwest Hawaii",
    station: "51002",
    id: 5,
    tag: "buoy",
    header: "Buoy Station 51002",
    meta: "SOUTHWEST HAWAII - 215NM SSW of Hilo, HI",
  },
  {
    name: "Southwest Hawaii",
    station: "51002",
    id: 6,
    tag: "power",
    header: "Wave Energy for Station 51002",
    meta: "SOUTHWEST HAWAII - 215NM SSW of Hilo, HI",
  },
  {
    name: "Southeast Hawaii",
    station: "51004",
    id: 7,
    tag: "buoy",
    header: "Buoy Station 51004",
    meta: "SOUTHEAST HAWAII - 205 NM Southeast of Hilo, HI",
  },
  {
    name: "Southeast Hawaii",
    station: "51004",
    id: 8,
    tag: "power",
    header: "Wave Energy for Station 51004",
    meta: "SOUTHEAST HAWAII - 205 NM Southeast of Hilo, HI",
  },
  {
    name: "Waimea Bay",
    station: "51201",
    id: 9,
    tag: "buoy",
    header: "Buoy Station 51201",
    meta: "Waimea Bay, HI",
  },
  {
    name: "Waimea Bay",
    station: "51201",
    id: 10,
    tag: "power",
    header: "Wave Energy for Station 51201",
    meta: "Waimea Bay, HI",
  },
  {
    name: "Honolulu",
    station: "1612340",
    id: 11,
    tag: "tide",
    header: "Tide Predictions at 1612340",
    meta: "Honolulu, HI",
  },
  {
    name: "Haleiwa",
    station: "1612668",
    id: 12,
    tag: "tide",
    header: "Tide Predictions at 1612668",
    meta: "Haleiwa, Waialua Bay, HI",
  },
  {
    name: "Overview",
    station: "0",
    id: 13,
    tag: "forecast",
    header: "All Islands OverviewForecast",
    meta: "Kauai, HI",
  },
  {
    name: "Kauai",
    station: "1",
    id: 14,
    tag: "forecast",
    header: "Kauai Forecast",
    meta: "Kauai, HI",
  },
  {
    name: "O'ahu",
    station: "2",
    id: 15,
    tag: "forecast",
    header: "Oahu Forecast",
    meta: "O'ahu, HI",
  },
  {
    name: "Maui",
    station: "3",
    id: 16,
    tag: "forecast",
    header: "Maui Forecast",
    meta: "Maui, HI",
  },
  {
    name: "Big Island Windward and Southeast",
    station: "4",
    id: 17,
    tag: "forecast",
    header: "Big Island Windward and Southeast",
    meta: "Hawaii, HI",
  },
  {
    name: "Big Island Leeward",
    station: "5",
    id: 18,
    tag: "forecast",
    header: "Big Island Leeward",
    meta: "Hawaii, HI",
  },
  {
    name: "Overview",
    station: "1",
    id: 19,
    tag: "marine-forecast",
    header: "Marine Forecast",
    meta: "Hawaiian Coastal Waters",
  },
  {
    name: "Kauai NorthWest Waters",
    station: "2",
    id: 20,
    tag: "marine-forecast",
    header: "",
    meta: "",
  },
  {
    name: "Kauai Windward Waters",
    station: "3",
    id: 21,
    tag: "marine-forecast",
    header: "",
    meta: "",
  },
  {
    name: "Kauai Leeward Waters",
    station: "4",
    id: 22,
    tag: "marine-forecast",
    header: "",
    meta: "",
  },
  {
    name: "Kauai Channel",
    station: "5",
    id: 23,
    tag: "marine-forecast",
    header: "",
    meta: "",
  },
  {
    name: "Oahu Windward Waters",
    station: "6",
    id: 24,
    tag: "marine-forecast",
    header: "",
    meta: "",
  },
  {
    name: "Oahu Leeward Waters",
    station: "7",
    id: 25,
    tag: "marine-forecast",
    header: "",
    meta: "",
  },
  {
    name: "Ka'iwi Channel",
    station: "8",
    id: 26,
    tag: "marine-forecast",
    header: "",
    meta: "",
  },
  {
    name: "Maui County Windward Waters",
    station: "9",
    id: 27,
    tag: "marine-forecast",
    header: "",
    meta: "",
  },
  {
    name: "Maui County Leeward Waters",
    station: "10",
    id: 28,
    tag: "marine-forecast",
    header: "",
    meta: "",
  },
  {
    name: "Ma'alaea Bay",
    station: "11",
    id: 29,
    tag: "marine-forecast",
    header: "",
    meta: "",
  },
  {
    name: "Pailolo Channel",
    station: "12",
    id: 30,
    tag: "marine-forecast",
    header: "",
    meta: "",
  },
  {
    name: "Alenuihaha Channel",
    station: "13",
    id: 31,
    tag: "marine-forecast",
    header: "",
    meta: "",
  },
  {
    name: "Big Island Windward Waters",
    station: "14",
    id: 32,
    tag: "marine-forecast",
    header: "",
    meta: "",
  },
  {
    name: "Big Island Leeward Waters",
    station: "15",
    id: 33,
    tag: "marine-forecast",
    header: "",
    meta: "",
  },
  {
    name: "Big Island Southeast Waters",
    station: "16",
    id: 34,
    tag: "marine-forecast",
    header: "",
    meta: "",
  },
  {
    name: "Pacific Ocean",
    station: "pac",
    id: 35,
    tag: "wave-model-period",
    header: "",
    meta: "",
  },
  {
    name: "North Pacific",
    station: "npac",
    id: 36,
    tag: "wave-model-period",
    header: "",
    meta: "",
  },
  {
    name: "South Pacific",
    station: "spac",
    id: 37,
    tag: "wave-model-period",
    header: "",
    meta: "",
  },
  {
    name: "Indian Ocean",
    station: "indi",
    id: 38,
    tag: "wave-model-period",
    header: "",
    meta: "",
  },
  {
    name: "North Atlantic",
    station: "natla",
    id: 39,
    tag: "wave-model-period",
    header: "",
    meta: "",
  },
  {
    name: "South Atlantic",
    station: "satla",
    id: 40,
    tag: "wave-model-period",
    header: "",
    meta: "",
  },
  {
    name: "Barber's Point",
    station: "51212",
    id: 41,
    tag: "buoy",
    header: "Buoy Station 51212",
    meta: "Barbers Point, Kalaeloa, HI",
  },
  {
    name: "Barber's Point",
    station: "51212",
    id: 42,
    tag: "power",
    header: "Wave Energy for Station 51212",
    meta: "Barbers Point, Kalaeloa, HI",
  },
  {
    name: "Hanapepe Bay",
    station: "1611347",
    id: 43,
    tag: "tide",
    header: "Tide Predictions at 1611347",
    meta: "Port Allen, Kauai, HI",
  },
  {
    name: "Hanauma Bay",
    station: "1612301",
    id: 44,
    tag: "tide",
    header: "Tide Predictions at 1612301",
    meta: "Waimanalo, HI",
  },
  {
    name: "Waianae",
    station: "1612482",
    id: 45,
    tag: "tide",
    header: "Tide Predictions at 1612482",
    meta: "Waianae, HI",
  },
  {
    name: "Pacific Ocean",
    station: "pac",
    id: 46,
    tag: "wave-model-height",
    header: "",
    meta: "",
  },
  {
    name: "North Pacific",
    station: "npac",
    id: 47,
    tag: "wave-model-height",
    header: "",
    meta: "",
  },
  {
    name: "South Pacific",
    station: "spac",
    id: 48,
    tag: "wave-model-height",
    header: "",
    meta: "",
  },
  {
    name: "Indian Ocean",
    station: "indi",
    id: 49,
    tag: "wave-model-height",
    header: "",
    meta: "",
  },
  {
    name: "North Atlantic",
    station: "natla",
    id: 50,
    tag: "wave-model-height",
    header: "",
    meta: "",
  },
  {
    name: "South Atlantic",
    station: "satla",
    id: 51,
    tag: "wave-model-height",
    header: "",
    meta: "",
  },
  {
    name: "Waimea",
    station: "106",
    id: 52,
    tag: "histogram",
    header: "A Wave Histogram",
    meta: "Waimea, HI",
  },
  {
    name: "Hanalei",
    station: "202",
    id: 53,
    tag: "histogram",
    header: "A Wave Histogram",
    meta: "Hanalei, HI",
  },
  {
    name: "Barber's Point",
    station: "238",
    id: 54,
    tag: "histogram",
    header: "A Wave Histogram",
    meta: "Kalaeloa, HI",
  },
  {
    name: "Hawaii",
    station: "hi-600-600",
    id: 55,
    tag: "hurricane",
    header: "Geocolor Composite",
    meta: "Hawaii, Pacific",
  },
  {
    name: "East Pacific Wide",
    station: "tpw-900-540",
    id: 56,
    tag: "hurricane",
    header: "Geocolor Composite",
    meta: "Eastern Pacific",
  },
  {
    name: "North-East Pacific",
    station: "np-900-540",
    id: 57,
    tag: "hurricane",
    header: "Geocolor Composite",
    meta: "North Eastern Pacific",
  },
  {
    name: "East Pacific",
    station: "eep-900-540",
    id: 58,
    tag: "hurricane",
    header: "Geocolor Composite",
    meta: "Eastern Pacific",
  },
  {
    name: "Nawiliwili",
    station: "1611400",
    id: 59,
    tag: "tide",
    header: "Tide Predictions at 1611400",
    meta: "Nawiliwili Harbor, Kalapaki Kauai",
  },
  {
    name: "Hanamaulu Bay",
    station: "1611443",
    id: 60,
    tag: "tide",
    header: "Tide Predictions at 1611443",
    meta: "Hanamaulu, Kauai",
  },
  {
    name: "North-West Hawaii",
    station: "PHKI",
    id: 61,
    tag: "hawaii-weather-radar-loop",
    header: "Hawaii Weather Radar Loop",
    meta: "Ni'ihau, Kaua'i, O'ahu",
  },
  {
    name: "Central Hawaii",
    station: "PHMO",
    id: 62,
    tag: "hawaii-weather-radar-loop",
    header: "Hawaii Weather Radar Loop",
    meta: "O'ahu, Moloka'i, Maui, Big Island",
  },
  {
    name: "South-East Hawaii",
    station: "PHKM",
    id: 63,
    tag: "hawaii-weather-radar-loop",
    header: "Hawaii Weather Radar Loop",
    meta: "Moloka'i, Maui, Big Island",
  },
  {
    name: "Big Island",
    station: "PHWA",
    id: 64,
    tag: "hawaii-weather-radar-loop",
    header: "Hawaii Weather Radar Loop",
    meta: "Maui, Big Island",
  },
  {
    name: "Hawaii",
    station: "HAWAII",
    id: 65,
    tag: "hawaii-weather-radar-loop",
    header: "Hawaii Weather Radar Loop",
    meta: "The Hawaiian Islands",
  },
  {
    name: "Niihau",
    station: "0",
    id: 66,
    tag: "weather-forecast",
    header: "",
    meta: "",
  },
  {
    name: "Kauai North",
    station: "1",
    id: 67,
    tag: "weather-forecast",
    header: "",
    meta: "",
  },
  {
    name: "Kauai East",
    station: "2",
    id: 68,
    tag: "weather-forecast",
    header: "",
    meta: "",
  },
  {
    name: "Kauai South",
    station: "3",
    id: 69,
    tag: "weather-forecast",
    header: "",
    meta: "",
  },
  {
    name: "Kauai Southwest",
    station: "4",
    id: 70,
    tag: "weather-forecast",
    header: "",
    meta: "",
  },
  {
    name: "Kauai Mountains",
    station: "5",
    id: 71,
    tag: "weather-forecast",
    header: "",
    meta: "",
  },
  {
    name: "East Honolulu",
    station: "6",
    id: 72,
    tag: "weather-forecast",
    header: "",
    meta: "",
  },
  {
    name: "Honolulu Metro",
    station: "7",
    id: 73,
    tag: "weather-forecast",
    header: "",
    meta: "",
  },
  {
    name: "Ewa Plain",
    station: "8",
    id: 74,
    tag: "weather-forecast",
    header: "",
    meta: "",
  },
  {
    name: "Waianae Coast",
    station: "9",
    id: 75,
    tag: "weather-forecast",
    header: "",
    meta: "",
  },
  {
    name: "Oahu North Shore",
    station: "10",
    id: 76,
    tag: "weather-forecast",
    header: "",
    meta: "",
  },
  {
    name: "Koolau Windward",
    station: "11",
    id: 77,
    tag: "weather-forecast",
    header: "",
    meta: "",
  },
  {
    name: "Koolau Leeward",
    station: "12",
    id: 78,
    tag: "weather-forecast",
    header: "",
    meta: "",
  },
  {
    name: "Olomana",
    station: "13",
    id: 79,
    tag: "weather-forecast",
    header: "",
    meta: "",
  },
  {
    name: "Central Oahu",
    station: "14",
    id: 80,
    tag: "weather-forecast",
    header: "",
    meta: "",
  },
  {
    name: "Waianae Mountains",
    station: "15",
    id: 81,
    tag: "weather-forecast",
    header: "",
    meta: "",
  },
  {
    name: "Molokai Windward",
    station: "16",
    id: 82,
    tag: "weather-forecast",
    header: "",
    meta: "",
  },
  {
    name: "Molokai Southeast",
    station: "17",
    id: 83,
    tag: "weather-forecast",
    header: "",
    meta: "",
  },
  {
    name: "Molokai North",
    station: "18",
    id: 84,
    tag: "weather-forecast",
    header: "",
    meta: "",
  },
  {
    name: "Molokai West",
    station: "19",
    id: 85,
    tag: "weather-forecast",
    header: "",
    meta: "",
  },
  {
    name: "Molokai Leeward South",
    station: "20",
    id: 86,
    tag: "weather-forecast",
    header: "",
    meta: "",
  },
  {
    name: "Lanai Windward",
    station: "21",
    id: 87,
    tag: "weather-forecast",
    header: "",
    meta: "",
  },
  {
    name: "Lanai Leeward",
    station: "22",
    id: 88,
    tag: "weather-forecast",
    header: "",
    meta: "",
  },
  {
    name: "Lanai South",
    station: "23",
    id: 89,
    tag: "weather-forecast",
    header: "",
    meta: "",
  },
  {
    name: "Lanai Mauka",
    station: "24",
    id: 90,
    tag: "weather-forecast",
    header: "",
    meta: "",
  },
  {
    name: "Kahoolawe",
    station: "25",
    id: 91,
    tag: "weather-forecast",
    header: "",
    meta: "",
  },
  {
    name: "Maui Windward West",
    station: "26",
    id: 92,
    tag: "weather-forecast",
    header: "",
    meta: "",
  },
  {
    name: "Maui Leeward West",
    station: "27",
    id: 93,
    tag: "weather-forecast",
    header: "",
    meta: "",
  },
  {
    name: "Maui Central Valley North",
    station: "28",
    id: 94,
    tag: "weather-forecast",
    header: "",
    meta: "",
  },
  {
    name: "Maui Central Valley South",
    station: "29",
    id: 95,
    tag: "weather-forecast",
    header: "",
    meta: "",
  },
  {
    name: "Windward Haleakala",
    station: "30",
    id: 96,
    tag: "weather-forecast",
    header: "",
    meta: "",
  },
  {
    name: "Kipahulu",
    station: "31",
    id: 97,
    tag: "weather-forecast",
    header: "",
    meta: "",
  },
  {
    name: "South Maui/UpCountry",
    station: "32",
    id: 98,
    tag: "weather-forecast",
    header: "",
    meta: "",
  },
  {
    name: "South Haleakala",
    station: "33",
    id: 99,
    tag: "weather-forecast",
    header: "",
    meta: "",
  },
  {
    name: "Haleakala Summit",
    station: "34",
    id: 100,
    tag: "weather-forecast",
    header: "",
    meta: "",
  },
  {
    name: "Kona",
    station: "35",
    id: 101,
    tag: "weather-forecast",
    header: "",
    meta: "",
  },
  {
    name: "Big Island South",
    station: "36",
    id: 102,
    tag: "weather-forecast",
    header: "",
    meta: "",
  },
  {
    name: "Big Island Southeast",
    station: "37",
    id: 103,
    tag: "weather-forecast",
    header: "",
    meta: "",
  },
  {
    name: "Big Island East",
    station: "38",
    id: 104,
    tag: "weather-forecast",
    header: "",
    meta: "",
  },
  {
    name: "Big Island North",
    station: "39",
    id: 105,
    tag: "weather-forecast",
    header: "",
    meta: "",
  },
  {
    name: "Kohala",
    station: "40",
    id: 106,
    tag: "weather-forecast",
    header: "",
    meta: "",
  },
  {
    name: "Big Island Interior",
    station: "41",
    id: 107,
    tag: "weather-forecast",
    header: "",
    meta: "",
  },
  {
    name: "Big Island Summits",
    station: "42",
    id: 108,
    tag: "weather-forecast",
    header: "",
    meta: "",
  },
];
