// AUTO-GENERATED FILE
// Run: npm run generate:lookup
// Do not edit by hand.

export const LOOKUP = {
  "BUOY": {
    "BARBERS_POINT": 41,
    "HANALEI": 1,
    "NORTH_WEST": 0,
    "SOUTHEAST_HAWAII": 7,
    "SOUTHWEST_HAWAII": 5,
    "WAIMEA_BAY": 9
  },
  "FORECAST": {
    "BIG_ISLAND_LEEWARD": 18,
    "BIG_ISLAND_WINDWARD_AND_SOUTHEAST": 17,
    "KAUAI": 14,
    "MAUI": 16,
    "OAHU": 15,
    "OVERVIEW": 13
  },
  "HAWAII_WEATHER_RADAR_LOOP": {
    "BIG_ISLAND": 64,
    "CENTRAL_HAWAII": 62,
    "HAWAII": 65,
    "NORTH_WEST_HAWAII": 61,
    "SOUTH_EAST_HAWAII": 63
  },
  "HISTOGRAM": {
    "BARBERS_POINT": 54,
    "HANALEI": 53,
    "WAIMEA": 52
  },
  "HURRICANE": {
    "EAST_PACIFIC": 58,
    "EAST_PACIFIC_WIDE": 56,
    "HAWAII": 55,
    "NORTH_EAST_PACIFIC": 57
  },
  "MARINE_FORECAST": {
    "ALENUIHAHA_CHANNEL": 31,
    "BIG_ISLAND_LEEWARD_WATERS": 33,
    "BIG_ISLAND_SOUTHEAST_WATERS": 34,
    "BIG_ISLAND_WINDWARD_WATERS": 32,
    "KAIWI_CHANNEL": 26,
    "KAUAI_CHANNEL": 23,
    "KAUAI_LEEWARD_WATERS": 22,
    "KAUAI_NORTHWEST_WATERS": 20,
    "KAUAI_WINDWARD_WATERS": 21,
    "MAALAEA_BAY": 29,
    "MAUI_COUNTY_LEEWARD_WATERS": 28,
    "MAUI_COUNTY_WINDWARD_WATERS": 27,
    "OAHU_LEEWARD_WATERS": 25,
    "OAHU_WINDWARD_WATERS": 24,
    "OVERVIEW": 19,
    "PAILOLO_CHANNEL": 30
  },
  "POWER": {
    "BARBERS_POINT": 42,
    "HANALEI": 4,
    "NORTH_WEST": 3,
    "SOUTHEAST_HAWAII": 8,
    "SOUTHWEST_HAWAII": 6,
    "WAIMEA_BAY": 10
  },
  "TIDE": {
    "HALEIWA": 12,
    "HANALEI": 2,
    "HANAMAULU_BAY": 60,
    "HANAPEPE_BAY": 43,
    "HANAUMA_BAY": 44,
    "HONOLULU": 11,
    "NAWILIWILI": 59,
    "WAIANAE": 45
  },
  "WAVE_MODEL_HEIGHT": {
    "INDIAN_OCEAN": 49,
    "NORTH_ATLANTIC": 50,
    "NORTH_PACIFIC": 47,
    "PACIFIC_OCEAN": 46,
    "SOUTH_ATLANTIC": 51,
    "SOUTH_PACIFIC": 48
  },
  "WAVE_MODEL_PERIOD": {
    "INDIAN_OCEAN": 38,
    "NORTH_ATLANTIC": 39,
    "NORTH_PACIFIC": 36,
    "PACIFIC_OCEAN": 35,
    "SOUTH_ATLANTIC": 40,
    "SOUTH_PACIFIC": 37
  },
  "WEATHER_FORECAST": {
    "BIG_ISLAND_EAST": 104,
    "BIG_ISLAND_INTERIOR": 107,
    "BIG_ISLAND_NORTH": 105,
    "BIG_ISLAND_SOUTH": 102,
    "BIG_ISLAND_SOUTHEAST": 103,
    "BIG_ISLAND_SUMMITS": 108,
    "CENTRAL_OAHU": 80,
    "EAST_HONOLULU": 72,
    "EWA_PLAIN": 74,
    "HALEAKALA_SUMMIT": 100,
    "HONOLULU_METRO": 73,
    "KAHOOLAWE": 91,
    "KAUAI_EAST": 68,
    "KAUAI_MOUNTAINS": 71,
    "KAUAI_NORTH": 67,
    "KAUAI_SOUTH": 69,
    "KAUAI_SOUTHWEST": 70,
    "KIPAHULU": 97,
    "KOHALA": 106,
    "KONA": 101,
    "KOOLAU_LEEWARD": 78,
    "KOOLAU_WINDWARD": 77,
    "LANAI_LEEWARD": 88,
    "LANAI_MAUKA": 90,
    "LANAI_SOUTH": 89,
    "LANAI_WINDWARD": 87,
    "MAUI_CENTRAL_VALLEY_NORTH": 94,
    "MAUI_CENTRAL_VALLEY_SOUTH": 95,
    "MAUI_LEEWARD_WEST": 93,
    "MAUI_WINDWARD_WEST": 92,
    "MOLOKAI_LEEWARD_SOUTH": 86,
    "MOLOKAI_NORTH": 84,
    "MOLOKAI_SOUTHEAST": 83,
    "MOLOKAI_WEST": 85,
    "MOLOKAI_WINDWARD": 82,
    "NIIHAU": 66,
    "OAHU_NORTH_SHORE": 76,
    "OLOMANA": 79,
    "SOUTH_HALEAKALA": 99,
    "SOUTH_MAUI_UPCOUNTRY": 98,
    "WAIANAE_COAST": 75,
    "WAIANAE_MOUNTAINS": 81,
    "WINDWARD_HALEAKALA": 96
  }
};
