import { LOOKUP } from "./generatedLookup";

export const PRESET_DEFINITIONS = {
  "North Shore": [
    LOOKUP.FORECAST.OAHU,
    LOOKUP.BUOY.NORTH_WEST,
    LOOKUP.POWER.NORTH_WEST,
    LOOKUP.TIDE.HALEIWA,
  ],

  "Kauai Surf": [
    LOOKUP.FORECAST.KAUAI,
    LOOKUP.BUOY.NORTH_WEST,
    LOOKUP.POWER.NORTH_WEST,
    LOOKUP.BUOY.HANALEI,
    LOOKUP.POWER.HANALEI,
    LOOKUP.TIDE.HANALEI,
    LOOKUP.HISTOGRAM.HANALEI,
  ],
};
