import { LOOKUP } from "./generatedLookup";

export const _ = LOOKUP;

export const PRESET_DEFINITIONS = {
  "North Shore": [
    _.FORECAST.OAHU,
    _.BUOY.NORTH_WEST,
    _.POWER.NORTH_WEST,
    _.TIDE.HALEIWA,
    _.WAVE_MODEL_PERIOD.NORTH_PACIFIC,
  ],
  "Kauai Surf": [
    _.FORECAST.KAUAI,
    _.BUOY.NORTH_WEST,
    _.POWER.NORTH_WEST,
    _.BUOY.HANALEI,
    _.POWER.HANALEI,
    _.TIDE.HANALEI,
    _.HISTOGRAM.HANALEI,
  ],
  "Oahu Surf": [
    _.FORECAST.OAHU,
    _.BUOY.NORTH_WEST,
    _.BUOY.BARBERS_POINT,
    _.TIDE.HONOLULU,
    _.TIDE.HALEIWA,
    _.TIDE.BARBERS_POINT,
    _.WAVE_MODEL_PERIOD.NORTH_PACIFIC,
    _.WAVE_MODEL_PERIOD.SOUTH_PACIFIC,
  ],
  "Hurricane Charts": [
    _.HURRICANE.HAWAII,
    _.HURRICANE.EAST_PACIFIC,
    _.HURRICANE.EAST_PACIFIC_WIDE,
    _.HURRICANE.NORTH_EAST_PACIFIC,
  ],
};
